const projects=[
{id:'001',title:'EchoVault',year:'2026',type:'Cinematic archive product',description:'Private vault interface for preserving voice notes, writings, and memory artifacts with calm navigation.',live:'https://nmethylpyrrolinium.github.io/echovault/',github:'https://github.com/nmethylpyrrolinium/echovault',slug:'projects/echovault.html',role:'Frontend + product direction',tools:'HTML, CSS, JS',problem:'Memory tools often feel clinical.',solution:'Built a warm archive system with clear retrieval and visual pacing.',features:['Searchable entries','Ambient visual hierarchy','Accessible keyboard paths'],reflection:'Emotion and clarity can coexist when interaction pacing is intentional.'},
{id:'002',title:'Asna Needle & Co.',year:'2026',type:'Brand commerce experience',description:'Tailoring brand site focused on craft storytelling, product confidence, and boutique conversion flow.',live:'https://nmethylpyrrolinium.github.io/asna-needle-and-co/',github:'https://github.com/nmethylpyrrolinium/asna-needle-and-co',slug:'projects/asna-needle.html',role:'Frontend + art direction',tools:'HTML, CSS, JS',problem:'Brand warmth was missing in standard templates.',solution:'Used editorial structure and tactile styling to mirror atelier craftsmanship.',features:['Service narratives','Visual catalog rhythm','Clear CTA hierarchy'],reflection:'Luxury tone requires restraint more than decoration.'},
{id:'003',title:'Ink of Arabia',year:'2025',type:'Editorial cultural microsite',description:'Narrative web essay around calligraphy, typography history, and digital ink composition.',live:'https://nmethylpyrrolinium.github.io/ink-of-arabia/',github:'',slug:'projects/ink-of-arabia.html',role:'Design + frontend',tools:'HTML, CSS',problem:'Long-form visual essays can become dense.',solution:'Structured pacing with typographic contrast and sectioned reading cues.',features:['Chapter navigation','Responsive image framing','Readable long-form layout'],reflection:'Cultural storytelling benefits from careful tempo and whitespace.'},
{id:'004',title:'Zyphoria',year:'2025',type:'Experimental landing',description:'Speculative interface experiment blending neon gradients with grounded conversion structure.',live:'https://nmethylpyrrolinium.github.io/zyphoria/',github:'https://github.com/nmethylpyrrolinium/zyphoria',slug:'projects/zyphoria.html',role:'Creative frontend',tools:'HTML, CSS, JS',problem:'Experimental visuals often reduce usability.',solution:'Balanced expressive motion with conventional interaction anchors.',features:['Focused hero CTA','Progressive reveals','Touch-friendly controls'],reflection:'Surreal aesthetics still need familiar navigation.'},
{id:'005',title:'Archive / Portfolio experiment',year:'2026',type:'Portfolio system',description:'This evolving archive portfolio, rebuilt for clarity, accessibility, and maintainability.',live:'https://nmethylpyrrolinium.github.io/gay-baboon/',github:'https://github.com/nmethylpyrrolinium/gay-baboon',slug:'projects/archive.html',role:'Frontend architecture + direction',tools:'HTML, CSS, JS',problem:'Original build was visually rich but structurally weak.',solution:'Split code, improved semantics, added real case-study narratives and robust mobile UX.',features:['Data-driven work cards','Accessible nav and focus states','Reduced intro friction'],reflection:'Atmosphere performs best when structure is disciplined.'}
];
const grid=document.getElementById('works-grid');
projects.forEach(p=>{const a=document.createElement('article');a.className='work-card';a.innerHTML=`<div class="meta">${p.id} · ${p.year} · ${p.type}</div><div class="thumb" role="img" aria-label="${p.title} preview artwork"></div><h3>${p.title}</h3><p>${p.description}</p><p class="meta"><strong>Role:</strong> ${p.role}<br><strong>Tools:</strong> ${p.tools}</p><div class="links-row">${p.live?`<a href="${p.live}">Live</a>`:''}${p.github?`<a href="${p.github}">GitHub</a>`:''}<a href="${p.slug}">Case study</a></div>`;grid.appendChild(a)});
const loader=document.getElementById('loader');
const closeLoader=()=>loader.classList.add('done');
window.addEventListener('load',()=>setTimeout(closeLoader,450));
document.getElementById('skip-loader').addEventListener('click',closeLoader);
const menuBtn=document.querySelector('.menu-toggle');const navLinks=document.getElementById('nav-links');
menuBtn.addEventListener('click',()=>{const exp=menuBtn.getAttribute('aria-expanded')==='true';menuBtn.setAttribute('aria-expanded',String(!exp));navLinks.classList.toggle('open');});
